### ISSUE TITLE
Class App\Http\Middleware\VerifyCsrfToken does not exist

### ISSUE THREAD

**Issue by neoroger** [petflow/laravel-5-api-boilerplate#1]
I did the steps:
```
# Cloned the respository
$ cp .env.testing .env
$ touch storage/testing.sqlite
$ php artisan migrate --env=testing
$ vendor/bin/codecept run
```

And when I try to access localhost I get the next error:

```
ReflectionException in Container.php line 776:
Class App\Http\Middleware\VerifyCsrfToken does not exist
```

**Comment by nkrantz23** [comment]
I'll be adding a new version today with some fixes and new stuff, for now you can just remove all the items in the $routeMiddleware array here:

https://github.com/petflow/laravel-5-api-boilerplate/blob/master/app/Http/Kernel.php

**Comment by neoroger** [comment]
Perfect!

**Comment by nkrantz23** [comment]
This version is fixed, with some sample code included: https://github.com/petflow/laravel-5-api-boilerplate/releases/tag/0.2.0

:)

**Comment by neoroger** [comment]
nice! I'm going to try that today.
By the way, have u thought about including an automated doc system such Swagger-php? I think it's a good tool for document an Api.
(Sorry if it isn't the place to put that suggestion, i'm very very noob on github. In fact this issue is my first "contribution" to github haha)

**Comment by nkrantz23** [comment]
Hey gotta start somewhere eh?

Swagger is a neat tool, I've picked up a lot of cool stuff from this book (including hearing about swagger and other auto-doc tools): https://leanpub.com/build-apis-you-wont-hate

Highly recommend!
